version: '3.5'
services:
  bot:
    image: gcr.io/docker-reghub/pyct-msgr
    command: >
              --port 3000
    env_file:
      - ../.env
    volumes:
      - ../../log:/log
    ports:
      - "3000:443"
    secrets:
      - source: account.json
        target: /app/private/account.json
      - source: fullchain.pem
        target: /app/private/ssl/fullchain.pem
      - source: privkey.pem
        target: /app/private/ssl/privkey.pem
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

secrets:
  account.json:
    file: ../private/account.json
  fullchain.pem:
    file: ../private/ssl/fullchain.pem
  privkey.pem:
    file: ../private/ssl/privkey.pem
